### ISSUE TITLE
Getting nothing but blank images on Linux

### ISSUE THREAD

**Issue by lesreaper** [Unity-Technologies/PeopleSansPeople#11]
```
Linux Ubuntu 22.04
nVidia CUDA 11.6
RTX 2080
Vulkan installed
nVidia-smi working
```

Downloaded the PeopleSans files into a test folder in my Documents folder as stated here:
https://github.com/Unity-Technologies/PeopleSansPeople/tree/main/peoplesanspeople_binaries

Downloaded the Standalone64 into the same folder, unzipped, and it placed everything in a `build ` folder in the PeopleSans temporary directory.

Ran command:
```
bash run.sh -t Linux -d /home/USER/path-to-PeopleSans/build/StandaloneLinux64 -f /home/USER/path-to-PeopleSans/scenarioConfiguration.json -l /home/USER/path-to-PeopleSans/build/StandaloneLinux64/log.txt
```

Generated 1.3 million blank images, segmentations, etc.

There are files in the dataset folder with JSON in it.

Log was never created.

Not sure what might be happening here.

**Comment by Saurav-D** [comment]
@lesreaper did you run this on your local linux machine or on a cloud vm? also, do you see the same behavior when generating smaller dataset (~1k frames)?

**Comment by lesreaper** [comment]
I had to use `CTRL-C` in the terminal to stop the program. It was going to keep going. As this was my first demo run, I don't know how to modify for smaller runs.

Local Linux machine, no vm.

**Comment by lesreaper** [comment]
Hey, that seemed to work!

I believe I can troubleshoot from here. Thank you!
