### ISSUE TITLE
Issue with importing animations to unity

### ISSUE THREAD

**Issue by cricket1** [Unity-Technologies/PeopleSansPeople#15]
I am using the peoplesanspeople_unity_env

There are 8 Unity-owned animation clips which work fine with animation randomizer.

But when I use animation from mixamo with animation randomizer, I see that only first frame of the animation is used in the generated images.

Is normal animation import using .fbx file sufficient ?

**Comment by salehe-ee** [comment]
Ensure that you import the .FBX for Unity animations. If you are using the `Simulation Scenario` with the `simulation config` file provided, it is currently set up to randomize the scene and only simulate one frame; so for each human character you will see a random pose applied to it. The animation randomizer randomly selects a random frame from a random animation from the set of animation clips you import. Hope this helps.
