### ISSUE TITLE
Suggestion : Guide to add custom object

### ISSUE THREAD

**Issue by GoGoPen** [Unity-Technologies/PeopleSansPeople#17]
I am not familiar with Unity. But I see that if there is guide to allow us to add custom objects. It will definite help researcher to build different artificial datasets.

**Comment by salehe-ee** [comment]
Thank you @GoGoPen for your interest in this work. There are many great resources available online on that topic that you can use. In addition to those, please see the [Unity Perception Package Tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Tutorial/TUTORIAL.md) and also the [Human Pose Labeling and Randomization Tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/HPTutorial/TUTORIAL.md) which should enable you to get started with bringing your own assets into Unity as well.
