### ISSUE TITLE
Writing one's own script to spawn humans at user-defined poses

### ISSUE THREAD

**Issue by hzyjerry** [Unity-Technologies/PeopleSansPeople#19]
Hi, thanks for the great project!

I'm wondering what's the best entry point to writing one's own script to generate images with self-defined human models/poses, and potentially with self-defined objects in the scenes.

The existing randomization code is really cool. Just wonder whether one can do more control in there.

Thanks!

**Comment by salehe-ee** [comment]
Hi @hzyjerry. Thanks for your interest in this project.

Adding your own human assets and animations is fairly straightforward in Unity. There are multiple formats you can use. Just need to ensure that they have the same attributes as the example assets provided. You may need some input from a Technical Artist to prepare your assets. I can recommend the [Human Pose Labeling](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/HumanPose/TUTORIAL.md) and the [Unity Perception](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Tutorial/TUTORIAL.md) tutorials as they explain these more in depth.

Hope that helps.

**Comment by salehe-ee** [comment]
Closing this for now. Please feel free to reopen if you had additional questions.
