### ISSUE TITLE
How to convert generated dataset to coco or yolo?

### ISSUE THREAD

**Issue by cansik** [Unity-Technologies/PeopleSansPeople#20]
I tried to convert a generated dataset into coco format by using [pysolotools](https://github.com/Unity-Technologies/pysolotools) but it seems that the `metadata.json` is missing. How can we generate the metadata file with the PeopleSansPeople project?

<img width="592" alt="image" src="https://user-images.githubusercontent.com/5220162/224072049-6988503c-bfa6-4b42-a9a8-1b65312c2b89.png">

**Comment by salehe-ee** [comment]
Seems like this question should be opened on the [pysolotools](https://github.com/Unity-Technologies/pysolotools) repo. It's a backwards compatibility issue that they need to address since PeopleSansPeople is built using Perception version 0.9.0-preview.2

**Comment by salehe-ee** [comment]
P.S. if it helps here we list the recommended approach for converting to COCO:
https://github.com/Unity-Technologies/PeopleSansPeople/tree/main/peoplesanspeople_unity_env#converting-the-simulations-generated-data-to-coco

**Comment by reydelsol** [comment]
FYI, I was able to avoid the error if I disabled the instance segmenting component in the Unity scene.
