### ISSUE TITLE
Any plan of releasing PSP-HDRI+?

### ISSUE THREAD

**Issue by cjerry1243** [Unity-Technologies/PeopleSansPeople#21]
Thank you for sharing the great work.
I was wondering if the release of PSP-HDRI+ is under your plan.

**Comment by salehe-ee** [comment]
Thank you for your interest in this work. Currently there are no plans of releasing the PSP-HDRI+. However, we have included detailed documentation in our paper, so that you can easily re-create it based on the template PSP Unity environment provided.
