### ISSUE TITLE
Add more images as texture background in peoplesanspeople_binaries

### ISSUE THREAD

**Issue by tungvd345** [Unity-Technologies/PeopleSansPeople#22]
Hi. Thank you for your great work.

I am not familiar with Unity. I would like to change the background when running peoplesanspeople_binaries.
How do I import more images to TextureRandomizer when running peoplesanspeople_binaries?

**Comment by salehe-ee** [comment]
Thank you for your interest in this work. This is not possible to do on the already-built binaries. You can follow the provided Unity template project and re-build the binaries after you've added your own textures.
