### ISSUE TITLE
Is it possible to generate 3D keypoint annotations?

### ISSUE THREAD

**Issue by isarandi** [Unity-Technologies/PeopleSansPeople#24]
Hi, this is a great project and I was wondering if it's also possible to output 3D keypoint labels besides the 2D ones described in the readme. Thanks!

**Comment by salehe-ee** [comment]
Thank you for your interest in this work. Currently this is not offered but by referring to the Unity Perception documentation you should be able to extend the keypoint labeler to output 3D coordinates in the camera view.
