### ISSUE TITLE
Generate data with OpenPose-format keypoints

### ISSUE THREAD

**Issue by thuyngch** [Unity-Technologies/PeopleSansPeople#6]
Hi authors,
Thanks for your great work!
I can follow instructions to generate data in COCO format with Linux binary file.

However, I would like to generate labels with OpenPose-format keypoints (25 keypoints) instead of COCO format (17 keypoints).
How can I do this?

Thanks,
Thuy

**Comment by salehe-ee** [comment]
Hi @thuyngch ! Thanks for your interest.
To generate keypoints in other formats, you need to do the following:

1. Ensure that your character has the additional joints necessary for the new format. You can follow this tutorial to add joints to the character in Unity.
https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/HPTutorial/TUTORIAL.md#step-5

2. Make sure that your character rig is working correctly, when animated etc. You can inspect the character rig by opening the character asset in Unity.

3. Then you need to ensure that the keypoint labeler is able to parse those additional joints. We have provided a few templates [here](https://github.com/Unity-Technologies/PeopleSansPeople/tree/main/peoplesanspeople_unity_env/Assets). For example you can change the keypoint skeletal structure in `peoplesanspeople_unity_env/Assets/CustomCocoKeypointTemplate.asset` and add/remove joints to it.

Hope this is helpful.

**Comment by thuyngch** [comment]
Hello @salehe-ee ,

Thanks for your support.
I can see the method for customizing joints.

But currently, I am using Unity GUI (personal version).
I import the project PeopleSansPeople, but there are two errors:
```
Library/PackageCache/com.unity.scripting.python@4.0.0-exp.5/Editor/PipPackages/PipPackages.cs(26,87): error CS0117: 'PythonSettings' does not contain a definition for 'kDefaultPython'
```
and
```
Library/PackageCache/com.unity.scripting.python@4.0.0-exp.5/Editor/PlatformCheck/PlatformCheck.cs(2,8): error CS1029: #error: 'The Python for Unity package is unsupported on the current platform'
```

My Unity version is 2020.3.20f1.
How can I fix it?

Thanks,
Thuy

**Comment by salehe-ee** [comment]
@thuyngch What platform are you on? 
I tried this on my end and I don't see those errors. Two things you may want to check:
1. After downloading the project, make sure that in Unity Hub you open the project at the [`peoplesanspeople_unity_env`](https://github.com/Unity-Technologies/PeopleSansPeople/tree/main/peoplesanspeople_unity_env) folder.

2. From Unity Hub, navigate to `Installs`; then from the settings for your installation of Unity `2020.3.20f1` open `Add Modules`. In that window please make sure you have downloaded `Linux Build Support (IL2CPP)` and `Linux Build Support (Mono)`.
<img width="1036" alt="Add Modules" src="https://user-images.githubusercontent.com/74270716/149060869-5364dd3b-c77c-46cf-8985-c23b9d011a88.png">

**Comment by thuyngch** [comment]
Hi @salehe-ee ,
Thanks for your instruction.

But I try to install more packages but it still got the errors.
This is my platform and I am using Ubuntu 21.10.

![Screenshot from 2022-01-13 08-49-31](https://user-images.githubusercontent.com/18340814/149251449-149e50f3-8554-4b1d-a1c5-51f344d86e36.png)

**Comment by thuyngch** [comment]
When opening the project, I got this message.

![Screenshot from 2022-01-13 09-16-59](https://user-images.githubusercontent.com/18340814/149254085-08dd39dc-4a8e-48df-b260-333e8f400c11.png)

**Comment by salehe-ee** [comment]
Hi @thuyngch. Sorry about the delay in responding. The Python for Unity package is currently not supported on Linux platforms. The latest commit https://github.com/Unity-Technologies/PeopleSansPeople/commit/224c2de71ff94f3798a616f8a02886fd0cd2e59d should fix this issue. Please let me know if there were any other problems.
