### ISSUE TITLE
39 Animation clips ?

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/PeopleSansPeople#7]
Thank you for sharing this great work first !.

I opened the project but I couldn't find the 39 animation clips so I wonder where I can find them.

I only found walk, running, jump, and idle animation clips.

Thank you.

**Comment by salehe-ee** [comment]
Thank you @moonsh for your interest in this work. In [the binary files](https://github.com/Unity-Technologies/PeopleSansPeople/tree/main/peoplesanspeople_binaries) we released 38 animations from Adobe Mixamo were used. However, we do not own the redistribution license for those. Therefore, the [Unity project we released](https://github.com/Unity-Technologies/PeopleSansPeople/tree/main/peoplesanspeople_unity_env) comes with 4 animations that we own. If you are interested in adding more animations you can source them from any animation repository of your choice, as long as they are in Unity FBX format. Hope this helps.
