### ISSUE TITLE
Keypoint visualization question

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/PeopleSansPeople#8]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/13994270/161137134-66b11b43-3951-47d9-8527-567586c7cd8c.png">

In this figure, it seems like keypoints for person_16 and person_24 are not accurately labeled. It's just a visualization issue?

**Comment by salehe-ee** [comment]
In COCO standard there is a concept for keypoint visibility (self-occlusion and occlusion by other objects). We follow the same standard in our keypoint labeling. In the Unity Editor's visualization, the keypoints that are occluded are not shown. For more information please refer to the [PeopleSansPeople paper](https://arxiv.org/abs/2112.09290) and [COCO](https://cocodataset.org/#format-data).
